#!/bin/sh
set -e
package_name=big-skel
mkdir -p "/usr/share/dpkgdivert/big-skel"
case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/big-skel/etcskel.bashrc" --rename "/etc/skel/.bashrc"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/etc/skel/.bashrc")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/big-skel/etcskel.bashrc" --rename "/etc/skel/.bashrc"
fi
;;
esac
exit 0
