#!/bin/sh
set -e
package_name=big-skel
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/etc/skel/.bashrc"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/etc/skel/.bashrc"
;;
esac
exit 0
